val TopWheel: Wheel = Seq(    Seq(None    , None    , None    , Some( 3)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , None    , Some( 6)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , None    , Some(10)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , None    , Some( 7)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , None    , Some(15)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , None    , Some( 8)),
                              Seq(None    , None    , None    , None    ))

val SecondWheel: Wheel = Seq( Seq(None    , None    , Some( 7), None    ),
                              Seq(None    , None    , Some(15), Some( 6)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , None    , Some(11)),
                              Seq(None    , None    , Some(14), Some(11)),
                              Seq(None    , None    , None    , Some( 6)),
                              Seq(None    , None    , Some( 9), Some(11)),
                              Seq(None    , None    , None    , None    ),
                              Seq(None    , None    , Some(12), Some( 6)),
                              Seq(None    , None    , None    , Some(17)),
                              Seq(None    , None    , Some( 4), Some( 7)),
                              Seq(None    , None    , None    , Some( 3)))

val MiddleWheel: Wheel = Seq( Seq(None    , Some( 5), Some(21), Some( 9)),
                              Seq(None    , None    , Some( 6), Some(13)),
                              Seq(None    , Some(10), Some(15), Some( 9)),
                              Seq(None    , None    , Some( 4), Some( 7)),
                              Seq(None    , Some( 8), Some( 9), Some(13)),
                              Seq(None    , None    , Some(18), Some(21)),
                              Seq(None    , Some(22), Some(11), Some(17)),
                              Seq(None    , None    , Some(26), Some( 4)),
                              Seq(None    , Some(16), Some(14), Some( 5)),
                              Seq(None    , None    , Some( 1), None    ),
                              Seq(None    , Some( 9), Some(12), Some( 7)),
                              Seq(None    , None    , None    , Some( 8)))

val FourthWheel: Wheel = Seq( Seq(Some( 6), Some( 9), Some(14), Some(14)),
                              Seq(None    , None    , Some(12), None    ),
                              Seq(Some(10), Some(17), Some( 3), Some(11)),
                              Seq(None    , Some(19), Some( 8), Some(11)),
                              Seq(Some(10), Some( 3), Some( 9), Some(14)),
                              Seq(None    , Some(12), None    , Some(11)),
                              Seq(Some( 1), Some( 3), Some( 9), Some(14)),
                              Seq(None    , Some(26), Some(20), Some(11)),
                              Seq(Some( 9), Some( 6), Some(12), Some(14)),
                              Seq(None    , None    , Some( 3), Some(14)),
                              Seq(Some(12), Some( 2), Some( 6), Some(11)),
                              Seq(None    , Some(13), None    , Some(14)))

val BottomWheel: Wheel = Seq( Seq(Some( 8), Some( 9), Some(15), Some(14)),
                              Seq(Some( 8), Some( 4), Some( 4), Some(11)),
                              Seq(Some( 3), Some( 4), Some( 5), Some(11)),
                              Seq(Some( 4), Some( 6), Some( 6), Some(14)),
                              Seq(Some(12), Some( 6), Some( 7), Some(11)),
                              Seq(Some( 2), Some( 3), Some( 8), Some(14)),
                              Seq(Some( 5), Some( 3), Some( 9), Some(11)),
                              Seq(Some(10), Some(14), Some(10), Some(14)),
                              Seq(Some( 7), Some(14), Some(11), Some(14)),
                              Seq(Some(16), Some(21), Some(12), Some(11)),
                              Seq(Some( 8), Some(21), Some(13), Some(14)),
                              Seq(Some( 7), Some( 9), Some(14), Some(11)))
